volumes:
  database_var:
  n8n_data:
  rabbitmq_var:

services:
  frankenphp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: php artisan octane:frankenphp --watch
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:18
    environment:
      - POSTGRES_DB=leavedb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - database_var:/var/lib/postgresql18/data

  n8n:
    image: n8nio/n8n
    ports:
      - target: 5678
        published: 5678
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - BACKEND_HOST=frankenphp
      - BACKEND_PORT=8000
    volumes:
      - n8n_data:/home/node/.n8n

  rabbitmq:
    image: rabbitmq:4.2.4-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_var:/var/lib/rabbitmq

  rabbit_consumer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: php artisan rabbitmq:consume
    depends_on:
      - frankenphp
      - rabbitmq

  job_work:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: php artisan queue:work -v
    depends_on:
      - database
